# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O5z-QDyCUjkOo-yqGQ-NCwNmvV8DQdNc
"""

n=.05
q=.25
d=.10
p=.01
nick=int(input("How many nickels do you have?"))
quart=int(input("How many quart do you have?"))
di=int(input("How many dimes do you have?"))
pen=int(input("How many pennies do you have?"))
total = nick*n + quart*q + di*d + pen*p
if total==1:
  print('You have one dollar, you have won the game!')
elif total<1 : 
  print("You were so close, your total was " , total) 
elif total>1:
  print("You were a bit too high, your total was ", total)
else:
  print("error try again")